### ISSUE TITLE
better display of rule, or don't display at all--let folks infer from cluster examples

### ISSUE THREAD

**Issue by eglassman** [lucasmf/refazer4education#20]
use wildcards if necessary?

**Comment by eglassman** [comment]
Alternative: use most common diff

**Comment by eglassman** [comment]
Feedback from user: not really necessary to display rule, especially since it's an imperfect, potentially misleading representation. His suggestion: let people infer rule from the cluster itself, which is what he was doing anyway.

**Comment by eglassman** [comment]
It's current just first example of its application, complete with indents

**Comment by ryosuzuki** [comment]
@eglassman What do you mean "rule"? Where does the current view show the rule?

**Comment by eglassman** [comment]
The current rule is displayed as the very first diff in the list of diffs generated by that rule. however, it does not communicate how general or specific that rule is. For example, some rules arbitrarily rename variables. A single example of a variable renaming doesn’t represent the rule accurately.

**Comment by ryosuzuki** [comment]
You mean, "rule" is the information shown in left panel? 
For example,
```diff
+ if n ==0:
+   return false
```
or
```diff
- if n==1:
+ if base==1:
```
something like that?

Is this issue also related to #21 ?
Sorry, I may still not understand it yet, so I want to make sure how I can fix it.

![screen shot 2016-09-23 at 10 16 44 pm](https://cloud.githubusercontent.com/assets/1428255/18806034/7401eb4a-81db-11e6-8e68-1a77bc06a2f9.png)

**Comment by eglassman** [comment]
Yes, that's the rule. No, it's not related to #21. Happy to chat about this over the phone or Skype on Sunday.

**Comment by eglassman** [comment]
This is not so important.

**Comment by ryosuzuki** [comment]
Close this issue for now since it seems not urgent or important. Re-open if necessary.
