### ISSUE TITLE
Show dynamic data inline (at point of differentiation from correctness), like Carbide

### ISSUE THREAD

**Issue by eglassman** [lucasmf/refazer4education#34]

**Comment by ryosuzuki** [comment]
Show the value of the data flow with the dynamic view.
Here is a current prototype. 

![7q71qznaxv](https://cloud.githubusercontent.com/assets/1428255/18985493/68237a94-86b5-11e6-97c1-7d2dbde2e08e.gif)

**Comment by ryosuzuki** [comment]
Here is a current prototype. 

![7q71qznaxv](https://cloud.githubusercontent.com/assets/1428255/18985493/68237a94-86b5-11e6-97c1-7d2dbde2e08e.gif)

**Comment by eglassman** [comment]
Very very very cool!
