### ISSUE TITLE
Click on cluster in the test tab

### ISSUE THREAD

**Issue by gustavoasoares** [lucasmf/refazer4education#58]
It is redirecting to the rule tab

**Comment by eglassman** [comment]
Actually, isn't it just hanging?

**Comment by eglassman** [comment]
@ryosuzuki, I noticed this when I pulled your most recent work. Do you not experience the same problem?

**Comment by eglassman** [comment]
Fixed! @gustavoasoares, you need to cd into static/react, run `npm install` and then `npm run build` and then it works.

**Comment by gustavoasoares** [comment]
Thanks @eglassman ! Now I can click on the tabs but I should have better described this bug:

- Click on the test tab
- Then click on some cluster in the left panel. It will redirect to the "rule" tab. I think it's just the link that is incorrect.

**Comment by gustavoasoares** [comment]
Fixed!
